### ISSUE TITLE
Build doesn't open on Android

### ISSUE THREAD

**Issue by kristopolous** [jaseemabid/micromanual#2]
I was unable to open the generated pdf on my Android phone. I've was able to view other pdfs before and after.

**Comment by jaseemabid** [comment]
Works on my phone. Can you provide more details? 

![screenshot_2016-03-07-14-21-34](https://cloud.githubusercontent.com/assets/601714/13564480/fc819380-e46f-11e5-9f63-5ad495541c64.png)

**Comment by RobertoMachorro** [comment]
OP hasn't commented further on the issue in ~3 years, can this be closed?

**Comment by jaseemabid** [comment]
@RobertoMachorro Sure.
