### ISSUE TITLE
The null list is () not 0

### ISSUE THREAD

**Issue by stuartpullinger** [jaseemabid/micromanual#5]
Lines 117-[118](https://github.com/jaseemabid/micromanual/blob/master/Micro%20Manual.tex#L118) in the tex file should read:

```... and \texttt{NIL} is the name of the null list ().```
rather than
```and \texttt{NIL} is the name of the null list 0.```

PS. Thanks for making this more legible version of the paper. 🥇

**Comment by jaseemabid** [comment]
Fixed at https://github.com/jaseemabid/micromanual/pull/6. Thanks @stuartpullinger
